# Generated by Django 4.1.3 on 2023-01-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App3D', '0004_canal_canalmensaje_canalusuario_delete_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tema', models.CharField(max_length=50)),
                ('Material', models.CharField(max_length=50)),
                ('Escala', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
