# Generated by Django 4.1.3 on 2023-01-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App3D', '0005_blog_delete_profesor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
